### ISSUE TITLE
Footer Buttons submit Form

### ISSUE THREAD

**Issue by RocketDav1d** [damianricobelli/shadcn-stepper#1]
First off, great component, thanks for building!
When using the Footer component inside a Form component clicking any Footer Button will result in the submit of the form

I found a workaround which effectively prevents the submission of the form
`
<Button size="sm" onClick={(event) => { if (!isLastStep) event.preventDefault(); nextStep(); }}>
  {isLastStep ? "Finish" : isOptionalStep ? "Skip" : "Next"}
</Button>
`

**Comment by RocketDav1d** [comment]
`<div className="w-full h-screen overflow-y-auto border border-blue-500">
      {showConfetti && <Confetti recycle={false} onConfettiComplete={handleConfettiComplete} />}
      <FormProvider {...methods}>
        <form className="h-screen py-4 pb-4" onSubmit={handleSubmit}>
          <div className="flex w-full flex-col gap-4">
            <Stepper
              initialStep={0}
              steps={steps}
              onClickStep={(step, setStep) => {
                alert(`Step ${step + 1} clicked`);
                setStep(step);
              }}
            >
              <Step key="Investment" label="Investment">
                <InvestmentStep
                  formData={formData}
                  setFormData={setFormData}
                  companyOption={companyOption}
                  setCompanyOption={setCompanyOption}
                  founderCompanies={founderCompanies}
                />
              </Step>
              <Step key="Kontaktaufnahme" label="Kontaktaufnahme">
                <KontaktaufnahmeStep formData={formData} setFormData={setFormData} />
              </Step>
              <Step key="Verhandlung" label="Verhandlung">
                <VerhandlungStep formData={formData} setFormData={setFormData} />
              </Step>
              <Step key="Fazit" label="Fazit">
                <FazitStep formData={formData} setFormData={setFormData} />
              </Step>
              <Footer handleSubmit={handleSubmit} />
            </Stepper>
          </div>
        </form>
      </FormProvider>
    </div>`
    
    
<img width="710" alt="Screenshot 2024-04-12 at 4 40 28 PM" src="https://github.com/damianricobelli/shadcn-stepper/assets/74053230/20646697-11be-4df3-9839-4cd41d67c68a">

    
same goes for when the steps itself are clicked
clicking a step will submit the Form

**Comment by damianricobelli** [comment]
Hey @RocketDav1d thank you very much and also for your comment. I will review this detail in the next few days

**Comment by damianricobelli** [comment]
@RocketDav1d could you give me a complete example of your use case?

**Comment by ruru-m07** [comment]
need more info to resolve

**Comment by CosAnca** [comment]
A `<button>` without an explicit `type` placed inside a `<form>` has by default `type="submit"` which will...submit the form. More details here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type
Shadcn UI `<Button>` component doesn't have a type assign to it by default, so you need to add `type="button"` to the `<Button>` component if you don't want it to submit the form.

**Comment by damianricobelli** [comment]
@CosAnca would you like to create a PR with the fix?

**Comment by ruru-m07** [comment]
> @CosAnca would you like to create a PR with the fix?

I don't think soo.

**Comment by abeisleem** [comment]
@ruru-m07, ez set button type=button

ex: 
```
<Button
  size="sm"
  type="button"
  onClick={(event) => {
    // if (!isLastStep) event.preventDefault(); // remove this preventDefault()
    nextStep();
  }}
>
  {' '}
  {isLastStep ? 'Finish' : isOptionalStep ? 'Skip' : 'Next'}{' '}
</Button>
```

**Comment by abeisleem** [comment]
Created a PR anyway to reflect this requirement in the form example

**Comment by damianricobelli** [comment]
Solved thanks to the fix in the example proposed by @abeisleem --> https://github.com/damianricobelli/shadcn-stepper/pull/6
