### ISSUE TITLE
How to use this stepper in my Shadcn Project ???

### ISSUE THREAD

**Issue by Thaheem001** [damianricobelli/shadcn-stepper#12]
please guide me how to integrate this stepper in my project???

**Comment by Thaheem001** [comment]
<img width="519" alt="image" src="https://github.com/damianricobelli/shadcn-stepper/assets/80126340/a15e5851-10b0-434b-a762-b2c7a77a7c07">

**Comment by skoruba** [comment]
would be nice to see some instruction, how to install it? or say what is required to copy to project etc.
thanks!

**Comment by Mahizha-N-S** [comment]
same error!!
is there any solution

**Comment by Davydhh** [comment]
Same error, did you find any solution?

**Comment by damianricobelli** [comment]
Hey guys! Sorry to tell you that the component is not yet ready in shadcn CLI as the PR has not yet been merged into main, so the only way to use it is by copying the code from this repository or the PR code into the shadcn repo

You can see the PR here --> https://github.com/shadcn-ui/ui/pull/318
