### ISSUE TITLE
Visible steps

### ISSUE THREAD

**Issue by rainbowdog1** [damianricobelli/shadcn-stepper#3]
Add a parameter to the main stepper, that will make all steps open/visible but disable those that are not completed.

For example:

There are 5 steps:
1st is visible and editable -> 2nd, 3rd, 4th, 5th are visible but disabled
After clicking next -> 1st and 2nd steps are visible and editable but others are disabled and etc.

**Comment by damianricobelli** [comment]
The component has the prop called `expandVerticalSteps`, which allows you to view all the steps. This would be useful to you?
