### ISSUE TITLE
Unhandled Runtime Error: 

### ISSUE THREAD

**Issue by Qodestackr** [damianricobelli/shadcn-stepper#5]
![image](https://github.com/damianricobelli/shadcn-stepper/assets/55054375/8b92c119-532c-4928-9abd-72b515d21906)

Error: (0 , _components_stepper__WEBPACK_IMPORTED_MODULE_1__.useStepper) is not a function

**Comment by damianricobelli** [comment]
Hey! Could you share a basic and functional example of your use case?

**Comment by balamurugan16** [comment]
I have faced this error, making the component a client component will solve this issue i guess. Give it a try!

**Comment by ojninja16** [comment]
yeah it works for all the examples where "use client " for making it into a client component is being used......where that's missing errors are happening...

**Comment by damianricobelli** [comment]
> I have faced this error, making the component a client component will solve this issue i guess. Give it a try!

Exactly. If you are using NextJS you need to tell the component "use client" otherwise you will see these errors mentioned in the issue. I'm closing the issue as I understand that this will fix it and is not part of a problem
