### ISSUE TITLE
I can't install the component

### ISSUE THREAD

**Issue by alvarobelmonte-satec** [damianricobelli/shadcn-stepper#9]
Hello,

I was trying to install this component as I do with every other shadcn component, but I can't figure it out how to do it. I get this error: 
![image](https://github.com/damianricobelli/shadcn-stepper/assets/98314321/e7e1dedc-77aa-426c-aea1-f412e5128da8)

Can anyone help me with this? Thank you in advance

**Comment by itsP33t** [comment]
Its not yet in the shadcn, its just a pull request now

**Comment by alvarobelmonte-satec** [comment]
@itsP33t I understand. I ended up copying the component from this repo. Thank you
